@url = http://localhost:3000/api/brands
@id = 645916aad73a2fe7b3e0e763

get {{url}}

###

get {{url}}/{{id}}

###

post {{url}}
Content-Type: application/json

{
    "name": "BMW",
    "country": "Germany",
    "founded": 1918
}

###

patch {{url}}/{{id}}
Content-Type: application/json

{
    "name": "BMW",
    "country": "Germany",
    "founded": "1916"
}
###

delete {{url}}/{{id}}