@url = http://localhost:3000/api/vehicles

get {{url}}

###

get {{url}}/64591c8a8051b97b6f3c9382

###

post {{url}}
Content-Type: application/json

{
    "brand": "64591714d73a2fe7b3e0e76c",
    "model": "C200",
    "year": 2019,
    "price": 120000
}

###

put {{url}}/6459134f4e561ccbe393e179
Content-Type: application/json

{
    "brand": "BMW",
    "model": "X5",
    "year": 2019,
    "price": 120000
}

###

delete {{url}}/645912e67eb34101661f22ce